name: Agregar Nueva Comunidad
description: Proponer una nueva comunidad Bitcoiner para incluir en el directorio de Veintiuno.lat
title: "[comunidad]: "
labels: [" nueva comunidad", " pendiente ubicaci贸n"]
body:
  - type: markdown
    attributes:
      value: |
        ##  Agregar Nueva Comunidad Tech
        
        Gracias por contribuir al directorio de comunidades de Latinoam茅rica. 
        Por favor completa la siguiente informaci贸n para que podamos revisar y agregar la comunidad.
        
        **Nota:** Todos los campos marcados con * son obligatorios.

  - type: input
    id: community_title
    attributes:
      label: Nombre de la Comunidad
      description: El nombre oficial de la comunidad
      placeholder: "ej. Bitcoin M茅xico, ONG Bitcoin Argentina, Bitcoin Chile"
    validations:
      required: true

  - type: textarea
    id: community_description
    attributes:
      label: Descripci贸n
      description: Una descripci贸n clara y concisa de la comunidad (m谩ximo 300 caracteres)
      placeholder: "Describe brevemente qu茅 hace la comunidad, sus objetivos principales y tipo de actividades que organizan..."
    validations:
      required: true

  - type: input
    id: community_link
    attributes:
      label: Enlace Web
      description: URL principal de la comunidad (sitio web, Discord, Telegram, Meetup, etc.)
      placeholder: "https://ejemplo.com"
    validations:
      required: true

  - type: input
    id: community_country
    attributes:
      label: Pa铆s
      description: Pa铆s donde est谩 ubicada la comunidad
      placeholder: "ej. Argentina, M茅xico, Colombia, Brasil"
    validations:
      required: true

  - type: input
    id: community_city
    attributes:
      label: Ciudad
      description: Ciudad principal donde opera la comunidad (opcional)
      placeholder: "ej. Buenos Aires, Ciudad de M茅xico, Bogot谩"

  - type: dropdown
    id: has_coordinates
    attributes:
      label: 驴Tienes las coordenadas de ubicaci贸n?
      description: Si conoces la latitud y longitud exactas de la comunidad
      options:
        - "S铆, tengo las coordenadas"
        - "No, necesito ayuda para obtenerlas"
    validations:
      required: true

  - type: input
    id: community_latitude
    attributes:
      label: Latitud
      description: Coordenada de latitud (solo si seleccionaste "S铆" arriba)
      placeholder: "ej. -34.6118 (para Buenos Aires)"

  - type: input
    id: community_longitude
    attributes:
      label: Longitud
      description: Coordenada de longitud (solo si seleccionaste "S铆" arriba)
      placeholder: "ej. -58.3960 (para Buenos Aires)"

  - type: markdown
    attributes:
      value: |
        ###  驴C贸mo obtener las coordenadas?
        
        Si no tienes las coordenadas, puedes obtenerlas f谩cilmente:
        
        **Opci贸n 1: Google Maps**
        1. Ve a [Google Maps](https://maps.google.com)
        2. Busca la ciudad o direcci贸n de la comunidad
        3. Haz clic derecho en el punto exacto del mapa
        4. Selecciona las coordenadas que aparecen en el men煤 (formato: latitud, longitud)
        
        **Opci贸n 2: Coordenadas GPS**
        1. Ve a [gps-coordinates.net](https://www.gps-coordinates.net)
        2. Busca la ubicaci贸n de la comunidad
        3. Copia las coordenadas en formato decimal
        
        **Opci贸n 3: OpenStreetMap**
        1. Ve a [OpenStreetMap](https://www.openstreetmap.org)
        2. Busca la ubicaci贸n
        3. Haz clic derecho y selecciona "Mostrar direcci贸n"
        4. Las coordenadas aparecer谩n en la URL
        
        **Formato esperado:**
        - Latitud: n煤mero decimal (ej. -34.6118)
        - Longitud: n煤mero decimal (ej. -58.3960)
        - Usa punto (.) como separador decimal, no coma (,)

  - type: checkboxes
    id: community_verification
    attributes:
      label: Verificaci贸n
      description: Confirma que has verificado la informaci贸n
      options:
        - label: "He verificado que la comunidad est谩 activa y organiza eventos regularmente"
          required: true
        - label: "He confirmado que el enlace web funciona correctamente"
          required: true
        - label: "La informaci贸n proporcionada es precisa y est谩 actualizada"
          required: true
        - label: "Esta comunidad no est谩 duplicada en el directorio actual"
          required: true

  - type: dropdown
    id: relationship
    attributes:
      label: Relaci贸n con la Comunidad
      description: 驴Cu谩l es tu relaci贸n con esta comunidad?
      options:
        - "Soy organizador/l铆der de la comunidad"
        - "Soy miembro activo de la comunidad"
        - "Conozco la comunidad pero no soy miembro"
        - "Encontr茅 la comunidad investigando"
        - "Otra"

  - type: textarea
    id: additional_info
    attributes:
      label: Informaci贸n Adicional
      description: Cualquier informaci贸n extra que consideres relevante sobre la comunidad
      placeholder: "ej. Frecuencia de eventos, n煤mero aproximado de miembros, colaboraciones especiales, etc."

  - type: markdown
    attributes:
      value: |
        ---
        
        ###  Pr贸ximos Pasos
        
        Una vez que env铆es este issue:
        
        1. **Revisi贸n**: Nuestro equipo revisar谩 la informaci贸n en 2-3 d铆as h谩biles
        2. **Validaci贸n**: Verificaremos que la comunidad est茅 activa y la informaci贸n sea correcta
        3. **Integraci贸n**: Si todo est谩 correcto, agregaremos la comunidad al directorio
        4. **Notificaci贸n**: Te notificaremos cuando la comunidad est茅 disponible en el mapa
        
        **驴Tienes dudas?** Puedes contactarnos en [hola@veintiuno.lat](mailto:hola@veintiuno.lat)
        
        隆Gracias por ayudar a hacer crecer el ecosistema tech de Latinoam茅rica! 